# Generated by Django 3.0 on 2022-02-18 10:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_registration', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(67), django.core.validators.MinValueValidator(14)])),
                ('layout', models.CharField(choices=[('2-2', 'Two By Two'), ('3-2', 'Three By Two')], default='3-2', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BusOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='logo-pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buupass.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buupass.Bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buupass.Route')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='buupass.BusOrganisation'),
        ),
    ]
