# Generated by Django 4.0.2 on 2022-02-15 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buupass', '0002_remove_bus_route_schedule_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='available',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(67), django.core.validators.MinValueValidator(14)]),
        ),
    ]
