# Generated by Django 4.0.2 on 2022-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buupass', '0005_remove_bus_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='layout',
            field=models.CharField(choices=[('2-2', 'Two By Two'), ('3-2', 'Three By Two')], default='3-2', max_length=3),
        ),
    ]
